networks:
  oozy-net:
    driver: bridge

services:
  web:
    image: caddy:latest
    container_name: oozy-web
    restart: unless-stopped
    ports:
      - "${WEB_PORT_HTTP}:80"
      - "${WEB_PORT_HTTPS}:443"
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./web/logs:/var/log/caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - oozy-net

  db:
    image: postgres:16-alpine
    container_name: oozy-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - oozy-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: oozy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - oozy-net
    depends-on:
      - db
      - web
